### ISSUE TITLE
[redux-ssr] Cant deploy to heroku

### ISSUE THREAD

**Issue by kybarg** [diegohaz/arc#183]
```
TypeError: callback is not a function
    at /tmp/build_cb4d0ff9f62cdadc09560de985dceac1/Trendberry-trendberry-arc-ef6b32e/node_modules/webpack/lib/Compiler.js:267:15
    at Compiler.emitRecords (/tmp/build_cb4d0ff9f62cdadc09560de985dceac1/Trendberry-trendberry-arc-ef6b32e/node_modules/webpack/lib/Compiler.js:362:37)
    at /tmp/build_cb4d0ff9f62cdadc09560de985dceac1/Trendberry-trendberry-arc-ef6b32e/node_modules/webpack/lib/Compiler.js:260:12
    at /tmp/build_cb4d0ff9f62cdadc09560de985dceac1/Trendberry-trendberry-arc-ef6b32e/node_modules/webpack/lib/Compiler.js:355:11
    at next (/tmp/build_cb4d0ff9f62cdadc09560de985dceac1/Trendberry-trendberry-arc-ef6b32e/node_modules/webpack/node_modules/tapable/lib/Tapable.js:154:11)
    at Compiler.compiler.plugin (/tmp/build_cb4d0ff9f62cdadc09560de985dceac1/Trendberry-trendberry-arc-ef6b32e/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/tmp/build_cb4d0ff9f62cdadc09560de985dceac1/Trendberry-trendberry-arc-ef6b32e/node_modules/webpack/node_modules/tapable/lib/Tapable.js:158:13)
    at Compiler.afterEmit (/tmp/build_cb4d0ff9f62cdadc09560de985dceac1/Trendberry-trendberry-arc-ef6b32e/node_modules/webpack/lib/Compiler.js:352:8)
    at Compiler.<anonymous> (/tmp/build_cb4d0ff9f62cdadc09560de985dceac1/Trendberry-trendberry-arc-ef6b32e/node_modules/webpack/lib/Compiler.js:347:14)
    at /tmp/build_cb4d0ff9f62cdadc09560de985dceac1/Trendberry-trendberry-arc-ef6b32e/node_modules/webpack/node_modules/async/dist/async.js:359:16
    at iteratorCallback (/tmp/build_cb4d0ff9f62cdadc09560de985dceac1/Trendberry-trendberry-arc-ef6b32e/node_modules/webpack/node_modules/async/dist/async.js:935:13)
    at /tmp/build_cb4d0ff9f62cdadc09560de985dceac1/Trendberry-trendberry-arc-ef6b32e/node_modules/webpack/node_modules/async/dist/async.js:843:16
    at /tmp/build_cb4d0ff9f62cdadc09560de985dceac1/Trendberry-trendberry-arc-ef6b32e/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by diegohaz** [comment]
Is that `universal-redux` or `redux-ssr`? The second isn't ready yet. 😝

**Comment by kybarg** [comment]
@diegohaz It's `redux-ssr` 😄 I guess need to wait then
