### ISSUE TITLE
deploying to heroku

### ISSUE THREAD

**Issue by mortenko** [diegohaz/arc#186]
Hi, Im trying to deploy on Heroku using command **git push heroku master** but I run into following issue : 
```
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  7.7.2
       engines.npm (package.json):   unspecified (use default)
       
       Downloading and installing node 7.7.2...
       Using default npm version: 4.1.2
       Resolving yarn version (latest) via semver.io...
       Downloading and installing yarn (0.21.3)...
       Installed yarn 0.21.3
-----> Restoring cache
       Skipping cache restore (new runtime signature)
-----> Building dependencies
       Installing node modules (yarn.lock)
       yarn install v0.21.3
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
       info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       [4/4] Building fresh packages...
       Done in 44.09s.
       Running heroku-postbuild (yarn)
       yarn run v0.21.3
       $ npm run build
       
       > arc@0.1.0 prebuild /tmp/build_e3b9e0c1ffeb0567e93faf2afd11e746
       > npm run build:clean && npm run build:copy
       
       
       > arc@0.1.0 build:clean /tmp/build_e3b9e0c1ffeb0567e93faf2afd11e746
       > rimraf "dist/!(.git*|Procfile)**"
       
       
       > arc@0.1.0 build:copy /tmp/build_e3b9e0c1ffeb0567e93faf2afd11e746
       > copyfiles -u 1 public/* public/**/* dist
       
       
       > arc@0.1.0 build /tmp/build_e3b9e0c1ffeb0567e93faf2afd11e746
       > cross-env NODE_ENV=production webpack --config webpack/webpack.config
       
module.js:472
    throw err;
    ^
Error: Cannot find module 'progress-bar-webpack-plugin'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function._module2.default._resolveFilename (/tmp/build_e3b9e0c1ffeb0567e93faf2afd11e746/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:423:34)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/build_e3b9e0c1ffeb0567e93faf2afd11e746/webpack/webpack.config.js:6:27)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
npm ERR! Linux 3.13.0-112-generic
npm ERR! argv "/tmp/build_e3b9e0c1ffeb0567e93faf2afd11e746/.heroku/node/bin/node" "/tmp/build_e3b9e0c1ffeb0567e93faf2afd11e746/.heroku/node/bin/npm" "run" "build"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! arc@0.1.0 build: `cross-env NODE_ENV=production webpack --config webpack/webpack.config`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the arc@0.1.0 build script 'cross-env NODE_ENV=production webpack --config webpack/webpack.config'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the arc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production webpack --config webpack/webpack.config
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs arc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls arc
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/build_e3b9e0c1ffeb0567e93faf2afd11e746/npm-debug.log
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - This project was built with yarn, which is new and under development. Some projects can still be built more reliably with npm
       https://devcenter.heroku.com/articles/nodejs-support#build-behavior
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

```
I have installed plugin progress-bar-webpack-plugin in my package.json devDependencies.

Im using node v7.2.2 and yarn as package manager. I run before pushing to heroku  command `yarn run build` but still it doesn't work. Any idea ?

**Comment by diegohaz** [comment]
Hey, @mortenko 

You need to move that dependency to production dependencies (a.k.a. `dependencies`) because Heroku will only install them.

It was addressed in 0f3a49fc38f96e444b2fc38fb938409c9bf79c18

**Comment by mortenko** [comment]
thank you.

**Comment by Rpaixao** [comment]
@diegohaz your answer has helped me, too! thanks
