### ISSUE TITLE
Deploying redux-ssr to Heroku

### ISSUE THREAD

**Issue by declanelcocks** [diegohaz/arc#298]
Hey, I'm trying to deploy the default `redux-ssr` branch and running into some errors. I thought it was an issue with my fork of the repo, so I've come back to your `redux-ssr` branch to see if it deploys ok, but I still get the same issue.

I've followed your deploy [guidelines](https://github.com/diegohaz/arc/wiki/Deploy) but I get this error when the app starts:

```
2017-06-28T08:13:38.000000+00:00 app[api]: Build succeeded
2017-06-28T08:14:17.449428+00:00 heroku[web.1]: Starting process with command `npm start`
2017-06-28T08:14:20.304902+00:00 heroku[web.1]: State changed from starting to crashed
2017-06-28T08:14:20.120593+00:00 app[web.1]: 
2017-06-28T08:14:20.120618+00:00 app[web.1]: > arc@0.1.0 start /app
2017-06-28T08:14:20.120619+00:00 app[web.1]: > node .
2017-06-28T08:14:20.120620+00:00 app[web.1]: 
2017-06-28T08:14:20.182210+00:00 app[web.1]: module.js:471
2017-06-28T08:14:20.182213+00:00 app[web.1]:     throw err;
2017-06-28T08:14:20.182214+00:00 app[web.1]:     ^
2017-06-28T08:14:20.182214+00:00 app[web.1]: 
2017-06-28T08:14:20.182238+00:00 app[web.1]: Error: Cannot find module '/app'
2017-06-28T08:14:20.182239+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:469:15)
2017-06-28T08:14:20.182240+00:00 app[web.1]:     at Function.Module._load (module.js:417:25)
2017-06-28T08:14:20.182241+00:00 app[web.1]:     at Module.runMain (module.js:604:10)
2017-06-28T08:14:20.182241+00:00 app[web.1]:     at run (bootstrap_node.js:389:7)
2017-06-28T08:14:20.182242+00:00 app[web.1]:     at startup (bootstrap_node.js:149:9)
2017-06-28T08:14:20.182243+00:00 app[web.1]:     at bootstrap_node.js:504:3
2017-06-28T08:14:20.190922+00:00 app[web.1]: 
2017-06-28T08:14:20.200512+00:00 app[web.1]: npm ERR! Linux 3.13.0-112-generic
2017-06-28T08:14:20.200823+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2017-06-28T08:14:20.201039+00:00 app[web.1]: npm ERR! node v6.11.0
2017-06-28T08:14:20.201244+00:00 app[web.1]: npm ERR! npm  v3.10.10
2017-06-28T08:14:20.201457+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-06-28T08:14:20.201633+00:00 app[web.1]: npm ERR! arc@0.1.0 start: `node .`
2017-06-28T08:14:20.201772+00:00 app[web.1]: npm ERR! Exit status 1
2017-06-28T08:14:20.201936+00:00 app[web.1]: npm ERR! 
2017-06-28T08:14:20.202088+00:00 app[web.1]: npm ERR! Failed at the arc@0.1.0 start script 'node .'.
2017-06-28T08:14:20.202226+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-06-28T08:14:20.202370+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the arc package,
2017-06-28T08:14:20.202624+00:00 app[web.1]: npm ERR! not with npm itself.
2017-06-28T08:14:20.202773+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2017-06-28T08:14:20.202922+00:00 app[web.1]: npm ERR!     node .
2017-06-28T08:14:20.203062+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-06-28T08:14:20.203202+00:00 app[web.1]: npm ERR!     npm bugs arc
2017-06-28T08:14:20.203344+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-06-28T08:14:20.203483+00:00 app[web.1]: npm ERR!     npm owner ls arc
2017-06-28T08:14:20.203669+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-06-28T08:14:20.207130+00:00 app[web.1]: 
2017-06-28T08:14:20.207342+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-06-28T08:14:20.207454+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-06-28T08:14:20.287842+00:00 heroku[web.1]: Process exited with status 1
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2017-06-28T08:14:20.202773+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2017-06-28T08:14:20.202922+00:00 app[web.1]: npm ERR!     node .
2017-06-28T08:14:20.203062+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-06-28T08:14:20.203202+00:00 app[web.1]: npm ERR!     npm bugs arc
2017-06-28T08:14:20.203344+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-06-28T08:14:20.203483+00:00 app[web.1]: npm ERR!     npm owner ls arc
2017-06-28T08:14:20.203669+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-06-28T08:14:20.207130+00:00 app[web.1]: 
2017-06-28T08:14:20.207342+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-06-28T08:14:20.207454+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-06-28T08:14:20.287842+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by declanelcocks** [comment]
I'm noticing that the dist folder will generate `client.js` though rather than `app.js` as shown in the wiki.

**Comment by declanelcocks** [comment]
Any ideas?

**Comment by diegohaz** [comment]
I'm investigating it. Sorry for the delay, @declanelcocks

**Comment by diegohaz** [comment]
You need to either remove `dist` from `.gitignore` or run `git add dist -f` before pushing to heroku. Thank you for reporting. Will add a note on Wiki.

**Comment by declanelcocks** [comment]
@diegohaz Haha, sorry as well because I should've spotted that. I actually looked for and missed the `dist` line in `.gitignore` which is a bit stupid of me. Thanks for solving it anyway!
