### ISSUE TITLE
About command "clean"

### ISSUE THREAD

**Issue by bluegeek** [diegohaz/arc#38]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\laragon\\bin\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.0.5
3 info using node@v6.9.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle arc@0.1.0~prebuild: arc@0.1.0
6 silly lifecycle arc@0.1.0~prebuild: no script for prebuild, continuing
7 info lifecycle arc@0.1.0~build: arc@0.1.0
8 verbose lifecycle arc@0.1.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle arc@0.1.0~build: PATH: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Administrator\Desktop\ccb\generator-reactpackage\scaff\node_modules\.bin;C:\Users\Administrator\AppData\Roaming\npm;C:\laragon\bin\cmder\vendor\telnet;C:\laragon\bin\cmder\vendor\putty;C:\Users\Administrator\AppData\Roaming\Composer\vendor\bin;C:\laragon\bin\mysql\mariadb-10.1.9\bin;C:\laragon\bin\php\php-7.0.12-Win32-VC14-x86;C:\laragon\bin\composer;C:\laragon\bin\apache\httpd-2.4.23-win32-VC14\bin;C:\laragon\bin\redis\redis-2.8.17;C:\laragon\bin\memcached\memcached-1.4.5;C:\laragon\bin\nodejs;C:\laragon\bin\nginx\nginx-1.10.1;C:\laragon\bin\notepad++;C:\laragon\bin\telnet;C:\laragon\bin\sublime;C:\laragon\bin\ngrok;C:\laragon\bin\sendmail;C:\laragon\bin\winscp;C:\laragon\bin\git\bin;C:\laragon\bin\git\cmd;C:\laragon\bin\git\usr\bin;C:\laragon\bin\git\mingw32\bin;C:\laragon\bin;C:\laragon\usr\bin;C:\laragon\bin\putty;C:\laragon\bin\cmder\bin;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Java\jdk1.8.0_111\bin;C:\Program Files (x86)\Java\jdk1.8.0_111\jre\bin;C:\Program Files\TortoiseSVN\bin;C:\laragon\bin\git\bin;C:\laragon\bin\php\php-7.0.12-Win32-VC14-x86;C:\laragon\bin\composer;C:\laragon\bin\nodejs;C:\Users\Administrator\AppData\Roaming\npm;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Local\atom\bin;;C:\Program Files (x86)\SSH Communications Security\SSH Secure Shell;C:\laragon\bin\cmder\;
10 verbose lifecycle arc@0.1.0~build: CWD: C:\Users\Administrator\Desktop\ccb\generator-reactpackage\scaff
11 silly lifecycle arc@0.1.0~build: Args: [ '/d /s /c',
11 silly lifecycle   'npm run clean && npm run copy && cross-env NODE_ENV=production webpack' ]
12 silly lifecycle arc@0.1.0~build: Returned: code: 1  signal: null
13 info lifecycle arc@0.1.0~build: Failed to exec build script
14 verbose stack Error: arc@0.1.0 build: `npm run clean && npm run copy && cross-env NODE_ENV=production webpack`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid arc@0.1.0
16 verbose cwd C:\Users\Administrator\Desktop\ccb\generator-reactpackage\scaff
17 error Windows_NT 10.0.14393
18 error argv "C:\\laragon\\bin\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.9.1
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error arc@0.1.0 build: `npm run clean && npm run copy && cross-env NODE_ENV=production webpack`
22 error Exit status 1
23 error Failed at the arc@0.1.0 build script 'npm run clean && npm run copy && cross-env NODE_ENV=production webpack'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the arc package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run clean && npm run copy && cross-env NODE_ENV=production webpack
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs arc
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls arc
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

when I run "npm run build",I got this error.
who can tell me what happend?

**Comment by diegohaz** [comment]
Maybe some Windows user could help you better. But it looks like you are doing everything on admin level. Running the prompt with administrator rights should solve the problem (but using admin user here seems a little weird)

**Comment by diegohaz** [comment]
Closing due to inactivity.
